version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    networks:
      otel-network:
        ipv4_address: 172.20.0.2

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      otel-network:
        ipv4_address: 172.20.0.3
    depends_on:
      - app

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./collector/config.yaml:/etc/otel/config.yaml
    command: ["--config", "/etc/otel/config.yaml"]
    ports:
      - "4317:4317"  # Puerto para gRPC
      - "4318:4318"  # Puerto para HTTP (OTLP)
      - "9464:9464"  # Puerto para métricas Prometheus
    networks:
      otel-network:
        ipv4_address: 172.20.0.4

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      otel-network:
        ipv4_address: 172.20.0.5
    depends_on:
      - collector

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      otel-network:
        ipv4_address: 172.20.0.6
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # HTTP (trazas)
      - "14250:14250"  # gRPC
    networks:
      otel-network:
        ipv4_address: 172.20.0.7

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      otel-network:
        ipv4_address: 172.20.0.8

networks:
  otel-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  portainer_data:
