receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: "http://localhost:4318/v1/traces"
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp, logging]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]
